Testing Dockerfiles
- With retry options

diff --git a/docker/Dockerfile.dev b/docker/Dockerfile.dev
--- a/docker/Dockerfile.dev
+++ b/docker/Dockerfile.dev
@@ -18,44 +18,73 @@ RUN for i in 1 2 3; do \
             iputils-ping \
         && rm -rf /var/lib/apt/lists/* \
         && break || { echo "Apt install failed, retrying ($i/3)..."; sleep 10; }; \
+        if [ "$i" -eq 3 ]; then exit 1; fi; \
     done
 
-RUN wget https://github.com/Kitware/CMake/releases/download/v3.22.5/cmake-3.22.5-linux-x86_64.sh \
-    && chmod +x cmake-3.22.5-linux-x86_64.sh \
-    && ./cmake-3.22.5-linux-x86_64.sh --skip-license --prefix=/usr/local \
-    && rm cmake-3.22.5-linux-x86_64.sh
+RUN for i in 1 2 3; do \
+        wget https://github.com/Kitware/CMake/releases/download/v3.22.5/cmake-3.22.5-linux-x86_64.sh \
+        && chmod +x cmake-3.22.5-linux-x86_64.sh \
+        && ./cmake-3.22.5-linux-x86_64.sh --skip-license --prefix=/usr/local \
+        && rm cmake-3.22.5-linux-x86_64.sh \
+        && break || { echo "CMake install failed, retrying ($i/3)..."; sleep 10; }; \
+        if [ "$i" -eq 3 ]; then exit 1; fi; \
+    done
 
-RUN wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 \
-    && tar -xjf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 \
-    && mv gcc-arm-none-eabi-10.3-2021.10 /usr/bin/gcc-arm-none-eabi \
-    && rm gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
+RUN for i in 1 2 3; do \
+        wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 \
+        && tar -xjf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 \
+        && mv gcc-arm-none-eabi-10.3-2021.10 /usr/bin/gcc-arm-none-eabi \
+        && rm gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 \
+        && break || { echo "GCC ARM install failed, retrying ($i/3)..."; sleep 10; }; \
+        if [ "$i" -eq 3 ]; then exit 1; fi; \
+    done
 
-RUN wget https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.2/clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04.tar.xz \
-    && tar -xf clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04.tar.xz \
-    && mv clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04 /usr/bin/llvm \
-    && rm clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04.tar.xz
+RUN for i in 1 2 3; do \
+        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.2/clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04.tar.xz \
+        && tar -xf clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04.tar.xz \
+        && mv clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04 /usr/bin/llvm \
+        && rm clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04.tar.xz \
+        && break || { echo "LLVM install failed, retrying ($i/3)..."; sleep 10; }; \
+        if [ "$i" -eq 3 ]; then exit 1; fi; \
+    done
 
-RUN wget https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/releases/download/release-19.1.1/LLVM-ET-Arm-19.1.1-Linux-x86_64.tar.xz \
-    && tar -xf LLVM-ET-Arm-19.1.1-Linux-x86_64.tar.xz \
-    && mv LLVM-ET-Arm-19.1.1-Linux-x86_64 /usr/bin/llvm-arm \
-    && rm LLVM-ET-Arm-19.1.1-Linux-x86_64.tar.xz
+RUN for i in 1 2 3; do \
+        wget https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/releases/download/release-19.1.1/LLVM-ET-Arm-19.1.1-Linux-x86_64.tar.xz \
+        && tar -xf LLVM-ET-Arm-19.1.1-Linux-x86_64.tar.xz \
+        && mv LLVM-ET-Arm-19.1.1-Linux-x86_64 /usr/bin/llvm-arm \
+        && rm LLVM-ET-Arm-19.1.1-Linux-x86_64.tar.xz \
+        && break || { echo "LLVM Embedded install failed, retrying ($i/3)..."; sleep 10; }; \
+        if [ "$i" -eq 3 ]; then exit 1; fi; \
+    done
 
-RUN curl -L https://github.com/numtide/treefmt/releases/download/v2.1.0/treefmt_2.1.0_linux_amd64.tar.gz -o treefmt.tar.gz \
-    && tar -xvzf treefmt.tar.gz \
-    && install -m 755 treefmt /usr/bin/treefmt \
-    && rm LICENSE README.md treefmt treefmt.tar.gz
+RUN for i in 1 2 3; do \
+        curl -L https://github.com/numtide/treefmt/releases/download/v2.1.0/treefmt_2.1.0_linux_amd64.tar.gz -o treefmt.tar.gz \
+        && tar -xvzf treefmt.tar.gz \
+        && install -m 755 treefmt /usr/bin/treefmt \
+        && rm LICENSE README.md treefmt treefmt.tar.gz \
+        && break || { echo "treefmt install failed, retrying ($i/3)..."; sleep 10; }; \
+        if [ "$i" -eq 3 ]; then exit 1; fi; \
+    done
 
-RUN curl -L https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-32d3ac78/clang-format-17_linux-amd64 -o usr/bin/clang-format-17 \
-    && chmod +x  usr/bin/clang-format-17
+RUN for i in 1 2 3; do \
+        curl -L https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-32d3ac78/clang-format-17_linux-amd64 -o usr/bin/clang-format-17 \
+        && chmod +x usr/bin/clang-format-17 \
+        && break || { echo "clang-format install failed, retrying ($i/3)..."; sleep 10; }; \
+        if [ "$i" -eq 3 ]; then exit 1; fi; \
+    done
 
 RUN pip3 install cmakelang
 
-RUN wget https://github.com/mozilla/sccache/releases/download/v0.10.0/sccache-v0.10.0-x86_64-unknown-linux-musl.tar.gz \
-    && tar -xzf sccache-v0.10.0-x86_64-unknown-linux-musl.tar.gz \
-    && mv sccache-v0.10.0-x86_64-unknown-linux-musl/sccache /usr/local/bin/sccache \
-    && chmod a+x /usr/local/bin/sccache \
-    && rm sccache-v0.10.0-x86_64-unknown-linux-musl.tar.gz \
-    && rm -rf sccache-v0.10.0-x86_64-unknown-linux-musl
+RUN for i in 1 2 3; do \
+        wget https://github.com/mozilla/sccache/releases/download/v0.10.0/sccache-v0.10.0-x86_64-unknown-linux-musl.tar.gz \
+        && tar -xzf sccache-v0.10.0-x86_64-unknown-linux-musl.tar.gz \
+        && mv sccache-v0.10.0-x86_64-unknown-linux-musl/sccache /usr/local/bin/sccache \
+        && chmod a+x /usr/local/bin/sccache \
+        && rm sccache-v0.10.0-x86_64-unknown-linux-musl.tar.gz \
+        && rm -rf sccache-v0.10.0-x86_64-unknown-linux-musl \
+        && break || { echo "sccache install failed, retrying ($i/3)..."; sleep 10; }; \
+        if [ "$i" -eq 3 ]; then exit 1; fi; \
+    done
 
 RUN git config --global --add safe.directory /home/jenkins
 ENV PATH="/usr/bin/gcc-arm-none-eabi/bin:/usr/bin/llvm/bin:/usr/bin/llvm-arm/bin:usr/bin/clang-format-17:usr/bin/treefmt:/usr/bin/gcc:/usr/local/bin/sccache${PATH}"
diff --git a/docker/Dockerfile.docs b/docker/Dockerfile.docs
--- a/docker/Dockerfile.docs
+++ b/docker/Dockerfile.docs
@@ -8,14 +8,19 @@ RUN for i in 1 2 3; do \
             bzip2 \
         && rm -rf /var/lib/apt/lists/* \
         && break || { echo "Apt install failed, retrying ($i/3)..."; sleep 10; }; \
+        if [ "$i" -eq 3 ]; then exit 1; fi; \
     done
 
 COPY doc/requirements.txt /tmp/requirements.txt
-RUN pip3 install -r /tmp/requirements.txt
+RUN  pip3 install -r /tmp/requirements.txt
 
-RUN wget https://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O /usr/local/bin/plantuml.jar \
-    && echo '#!/bin/sh\njava -jar /usr/local/bin/plantuml.jar "$@"' > /usr/local/bin/plantuml && \
-    chmod +x /usr/local/bin/plantuml
+RUN for i in 1 2 3; do \
+        wget https://sourceforge.net/projects/plantuml/files/plantuml.jar/download -O /usr/local/bin/plantuml.jar && \
+        echo '#!/bin/sh\njava -jar /usr/local/bin/plantuml.jar "$@"' > /usr/local/bin/plantuml && \
+        chmod +x /usr/local/bin/plantuml && \
+        break || { echo "PlantUML install failed, retrying ($i/3)..."; sleep 10; }; \
+        if [ "$i" -eq 3 ]; then exit 1; fi; \
+    done
 
 RUN pip3 install coverxygen
 
