Skip stats related test for posix-threadx as stats commands are not currently supported
Change-Id: Ia53674da66469add21d4d3215f071043b7e8c408

diff --git a/.github/workflows/run-pytest-on-posix.yml b/.github/workflows/run-pytest-on-posix.yml
--- a/.github/workflows/run-pytest-on-posix.yml
+++ b/.github/workflows/run-pytest-on-posix.yml
@@ -41,6 +41,9 @@ jobs:
           outputs: type=docker
           cache-from: type=gha
           cache-to: type=gha,mode=max,ignore-error=true
+      
+      - name: Check TUN device
+        run: ls -l /dev/net/tun || echo "TUN device missing"
 
       - name: Set up virtual ethernet interface
         run: |
